[phases.setup]
nixPkgs = ["nodejs", "postgresql"]

[phases.install]
cmds = ["cd backend && npm install", "cd backend && npm run db:generate"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && npm start" 